djangit/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
]

djangit/djangit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home, name='home'),
]

djangit/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
    # Up voting
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
    url(r'^user/(?P<uid>[0-9]+)', views.userposts, name='userposts'),
]

djangit/accounts/models.py
from django.db import models

# Create your models here.

djangit/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
  title = models.CharField(max_length=200)
  url = models.TextField()
  publish_date = models.DateTimeField()
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  votes_total = models.IntegerField(default=1)

  def publish_date_pretty(self):
    return self.publish_date.strftime('%b %e %Y')

djangit/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

# Create your views here.
def signup(request):
  if request.method == 'POST':
    if request.POST['password'] == request.POST['confirmpw']:
      try:
        user = User.objects.get(username=request.POST['username'])
        return render(request, 'accounts/signup.html', {'error':'Username has already been taken!'})
      except User.DoesNotExist:
        user = User.objects.create_user(
          request.POST['username'], 
          password = request.POST['password'])
        auth_login(request, user)
        return render(request, 'accounts/signup.html', {'success':'Your account of username "' + user.username + '" has been created.'})
    else:
      return render(request, 'accounts/signup.html', {'error':'Passwords didn\'t match.'})
  else:
    return render(request, 'accounts/signup.html')

def login(request):
  if request.method == 'POST':
    user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
    if user is not None:
      auth_login(request, user)
      if 'next' in request.POST:
        if request.POST['next'] is not None:
            return redirect(request.POST['next'])
      # Redirect to a success page.
      return redirect('home')
    else:
      # Return an 'invalid login' error message.
      return render(request, 'accounts/login.html', {'error':'Username and/or password didn\'t match!'})
  else:
    return render(request, 'accounts/login.html')

def logout(request):
  if request.method == 'POST':
    auth_logout(request)
    return redirect('home')

djangit/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post
from django.contrib.auth.models import User

# Create your views here.
@login_required
def create(request):
  if request.method == 'POST':
    if request.POST['title'] and request.POST['url']:
      # Create new Post object (from models)
      post = Post()
      post.title = request.POST['title']
      # Check for http(s)
      if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
        post.url = request.POST['url']
      else:
        post.url = 'http://' + request.POST['url']
      post.publish_date = timezone.now()
      post.author = request.user
      post.save()
      return redirect('home')
    else: # some error
      return render(request, 'posts/create.html', {'error':'ERROR: You must include a title and a URL to create a post.'})
  else: # GET
    return render(request, 'posts/create.html')

def home(request):
  posts = Post.objects.order_by('-votes_total')
  return render(request, 'posts/home.html', {'posts':posts})

def upvote(request, pk):
  if request.method == 'POST':
    post = Post.objects.get(pk=pk)
    # Increment votes
    post.votes_total += 1
    post.save()
    user_id = -1
    if 'uid' in request.POST.keys() and request.POST['uid']:
      user_id = request.POST['uid']
    if user_id != -1:
      return redirect('posts:userposts', uid=user_id)
    else:
      return redirect('home')

def downvote(request, pk):
  if request.method == 'POST':
    post = Post.objects.get(pk=pk)
    # Decrement votes
    post.votes_total += -1
    post.save()
    user_id = -1
    if 'uid' in request.POST.keys() and request.POST['uid']:
      user_id = request.POST['uid']
    if user_id != -1:
      return redirect('posts:userposts', uid=user_id)
    else:
      return redirect('home')

def userposts(request, uid):
  user = get_object_or_404(User, pk=uid)
  posts = Post.objects.filter(author_id=uid).order_by('-votes_total')
  return render(request, 'posts/userposts.html', {'user':user, 'posts':posts})

djangit/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login</h1>
{% if error %}
{{ error }}
<br><br>
{% endif %}
{% if success %}
{{ success }}
<br><br>
{% endif %}
<form action="{% url 'accounts:login' %}" method="POST">
  {% csrf_token %}
  {% if request.GET.next %}
  <input type="hidden" name="next" value={{request.GET.next}} />
  {% endif %}
  <div class="form-group">
    <label for="username-input">Username</label>
    <input id="username-input" class="form-control" type="text" name="username" placeholder="Enter username" />
  </div>
  <div class="form-group">
    <label for="password-input">Password</label>
    <input id="password-input" class="form-control" type="password" name="password" placeholder="Enter password"/>
  </div>
  <input class="btn btn-primary" type="submit" value="Login">
</form>

{% endblock %}

djangit/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>Sign Up for User Account</h1>
{% if error %}
{{ error }}
<br><br>
{% endif %}
{% if success %}
{{ success }}
<br><br>
{% endif %}
<form action="{% url 'accounts:signup' %}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="username-input">Username</label>
    <input id="username-input" class="form-control" type="text" name="username" placeholder="Enter username" />
  </div>
  <div class="form-group">
    <label for="password-input">Password</label>
    <input id="password-input" class="form-control" type="password" name="password" placeholder="Enter password"/>
  </div>
  <div class="form-group">
    <label for="confirmpw-input">Password</label>
    <input id="confirmpw-input" class="form-control" type="password" name="confirmpw" placeholder="Confirm password"/>
  </div>
  <input class="btn btn-primary" type="submit" value="Sign up!">
</form>

{% endblock %}

djangit/posts/templates/posts/create.html
{% extends 'base.html' %}
{% block content %}

<h1>New Post</h1>
{% if error %}
{{ error }}
<br><br>
{% endif %}
{% if success %}
{{ success }}
<br><br>
{% endif %}
<form action="{% url 'posts:create' %}" method="POST">
  {% csrf_token %}
  <input type="text" name="title" placeholder="Enter title" />
  <br>
  <input type="text" name="url" placeholder="Enter url"/>
  <br>
  <input type="submit" value="Post">
</form>

{% endblock %}

djangit/posts/templates/posts/home.html
{% extends 'base.html' %}
{% block content %}
<h1>The home page of djangit.</h1>
<a class="btn btn-primary" href="{% url 'posts:create' %}">New Post</a>
<br>
<br>

{% for post in posts.all %}
<table>
  <tr>
    <td style="padding-right: 20px;">
      <form method="POST" action="{% url 'posts:upvote' post.id %}" id="upvote-{{post.id}}">
        {% csrf_token %}
        <input type="hidden" value="UP">
      </form> 
      <a href="#" onclick="document.getElementById('upvote-{{post.id}}').submit()"><i class="fas fa-caret-up fa-2x"></i></a>
      <br>
      <span>{{ post.votes_total }}</span>
      <br>
      <form method="POST" action="{% url 'posts:downvote' post.id %}" id="downvote-{{post.id}}">
        {% csrf_token %}
        <input type="hidden" value="DOWN">
      </form>
      <a href="#" onclick="document.getElementById('downvote-{{post.id}}').submit()"><i class="fas fa-caret-down fa-2x"></i></a>
      
    </td>
    <td>
      <a href="{{ post.url }}" target="_blank">{{ post.title }}</a>
      <br>
      {{ post.publish_date_pretty }} by <a href="{% url 'posts:userposts' post.author.id %}">{{ post.author.username }}</a>
    </td>
  </tr>
</table>
<hr>
{% endfor %}

{% endblock %}

djangit/posts/templates/posts/userposts.html
{% extends 'base.html' %}
{% block content %}

<h1>These are the posts for {{ user.username }}</h1>

{% for post in posts.all %}
<table>
  <tr>
    <td style="padding-right: 20px;">
      <form method="POST" action="{% url 'posts:upvote' pk=post.id %}" id="upvote-{{post.id}}">
        {% csrf_token %}
        <input type="hidden" name='uid' value={{user.id}}>
        <input type="hidden" value="UP">
      </form> 
      <a href="#" onclick="document.getElementById('upvote-{{post.id}}').submit()"><i class="fas fa-caret-up fa-2x"></i></a>
      <br>
      <span>{{ post.votes_total }}</span>
      <br>
      <form method="POST" action="{% url 'posts:downvote' pk=post.id %}" id="downvote-{{post.id}}">
        {% csrf_token %}
        <input type="hidden" name='uid' value={{user.id}}>
        <input type="hidden" value="DOWN">
      </form>
      <a href="#" onclick="document.getElementById('downvote-{{post.id}}').submit()"><i class="fas fa-caret-down fa-2x"></i></a>
      
    </td>
    <td>
      <a href="{{ post.url }}" target="_blank">{{ post.title }}</a>
      <br>
      {{ post.publish_date_pretty }} by <a href="{% url 'posts:userposts' post.author.id %}">{{ post.author.username }}</a>
    </td>
  </tr>
</table>
<hr>
{% endfor %}

{% endblock %}

djangit/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <title>djangit</title>
  </head>
  <body>
    <!-- Just an image -->
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">
          djangit
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNav" aria-controls="myNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="myNav">
          <ul class="navbar-nav justify-content-end">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
          </ul>
        </div>
        <ul class="nav justify-content-end">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <form method="POST" action="{% url 'accounts:logout' %}" id="logout-form">
              {% csrf_token %}
              <input type="hidden">
            </form>
            <a class="nav-link" href="#" onclick="document.getElementById('logout-form').submit()">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>